language: perl

perl:
 - "5.10"
 - "5.12"
 - "5.14"
 - "5.16"
 - "5.18"

install:
 - cpanm --notest Dist::Zilla Dist::Zilla::PluginBundle::Author::ALEXBIO Dist::Zilla::Plugin::OSPrereqs Pod::Coverage::TrustPod Math::Int64
 - dzil listdeps --missing | cpanm --notest

script:
 - dzil smoke --release

notifications:
  recipient:
   - alessandro@ghedini.me
  email:
    on_success: change
    on_failure: always
